FROM node:lts-alpine

RUN mkdir -p /laetis-diner-api
COPY . /laetis-diner-api
WORKDIR /laetis-diner-api

RUN set -ex; \
    apk add postgresql-client; \
    yarn global add knex pg;

RUN yarn install

ENV NODE_ENV=production

COPY . /laetis-diner-api

EXPOSE 5000