version: "3"
services:
  laetis-diner-api:
    command: yarn dev
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgres://paul:postgres@db:5432/laetis_diner
    volumes:
      - .:/laetis-diner-api

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: paul
      POSTGRES_PASSWORD: postgres